// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1erxrq4I9_U3Z1fduNUSO6oFC10vnDGo',
    appId: '1:264754676317:web:38d5571e205f4b1fc783b4',
    messagingSenderId: '264754676317',
    projectId: 'mojo-b4260',
    authDomain: 'mojo-b4260.firebaseapp.com',
    storageBucket: 'mojo-b4260.firebasestorage.app',
    measurementId: 'G-NP8HRGZ6RJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_-Od2f5PbbehTeFbs7H9dMOvgELTSoi4',
    appId: '1:264754676317:android:ccf2b1659d3915dac783b4',
    messagingSenderId: '264754676317',
    projectId: 'mojo-b4260',
    storageBucket: 'mojo-b4260.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVYI6OOGJS1tjSUgxiQvJrztXQKcoxpWQ',
    appId: '1:264754676317:ios:98b9702a885c3b9cc783b4',
    messagingSenderId: '264754676317',
    projectId: 'mojo-b4260',
    storageBucket: 'mojo-b4260.firebasestorage.app',
    iosBundleId: 'com.example.mojo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVYI6OOGJS1tjSUgxiQvJrztXQKcoxpWQ',
    appId: '1:264754676317:ios:98b9702a885c3b9cc783b4',
    messagingSenderId: '264754676317',
    projectId: 'mojo-b4260',
    storageBucket: 'mojo-b4260.firebasestorage.app',
    iosBundleId: 'com.example.mojo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1erxrq4I9_U3Z1fduNUSO6oFC10vnDGo',
    appId: '1:264754676317:web:1bb0831778c877d9c783b4',
    messagingSenderId: '264754676317',
    projectId: 'mojo-b4260',
    authDomain: 'mojo-b4260.firebaseapp.com',
    storageBucket: 'mojo-b4260.firebasestorage.app',
    measurementId: 'G-W8ERTKGR9X',
  );
}
