name: mojo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'  # Relax constraint to support your Flutter version

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.0
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3
  firebase_messaging: ^15.1.3
  cloud_functions: ^5.3.3

  # State Management
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.1  # Specify a stable version

  # Utilities
  logger: ^2.0.2+1
  equatable: ^2.0.5
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  rxdart: ^0.27.7

  # UI & Interactions
  lottie: ^3.3.1  # Update to latest
  table_calendar: ^3.2.0
  image_picker: ^1.0.7
  flutter_local_notifications: ^17.2.2

  # Export & File Management
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  share_plus: ^7.2.2

  # Fonts
  google_fonts: ^6.2.1
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/animations/